spring:
  application:
    name: etext-manager
  session:
    store-type: none
  config.import: optional:${app.fullFilePath}/${app.overridesFileName}, optional:${app.fullFilePath}/security.properties, classpath:canvas.properties, optional:classpath:git.properties, classpath:lti-registrations.properties,optional:classpath:email.properties,optional:classpath:derdack.properties,
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${oauth.tokenprovider.url}/.well-known/jwks.json
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        temp:
          use_jdbc_metadata_defaults: false
      jadira:
        usertype:
          autoRegisterUserTypes: true
  datasource:
    url: ${lms.db.url}
    username: ${lms.db.user}
    password: ${lms.db.password}
    type: ${lms.db.poolType}
  cloud.vault.enabled: false
  data.rest.basePath: /rest
  rabbitmq:
    addresses: ${lms.rabbitmq.address.${app.env}}
    username: ${lms.rabbitmq.username.${app.env}}
    password: ${lms.rabbitmq.password.${app.env}}
    virtualHost: ${lms.rabbitmq.virtualHost.${app.env}}
    listener.simple:
      acknowledge-mode: manual
      missing-queues-fatal: false
      retry:
        enabled: true
        initial-interval: 3s
        max-attempts: 3
        max-interval: 10s
        multiplier: 2
etextmanager:
  version: @app.version@
  env: ${app.env}
  backgroundQueueName: etext_queue_${lms.rabbitmq.queue_env_suffix}
  groupCode: ELS
  defaultEmails: [iu-uits-es-ess-lms-notify@exchange.iu.edu]
  # toolSecrets will come from Vault
  toolSecrets: {}

server:
  error:
    whitelabel:
      enabled: false
  servlet:
    session:
      timeout: 30m

app:
  env: dev
  fullFilePath: file:/usr/src/app/config
  overridesFileName: overrides.properties

management:
  endpoint.lms.enabled: true
  endpoints.web.exposure.include: health,lms
  health.redis.enabled: false
  info.java.enabled: true

---

spring:
  config.activate.on-profile: redis-session
  session:
    store-type: redis
    redis.namespace: etext-manager-@app.version@:session
management.health.redis.enabled: true
---

spring:
  config:
    activate.on-profile: vault
    import: vault://
  cloud.vault:
    enabled: true
    config:
      lifecycle.lease-endpoints: leases
    generic:
      enabled: false
    kv:
      enabled: true
      backend: ua-vpit/enterprise-systems/lms/kv
      profiles: all, ${app.env}
      application-name: etext-manager

---

spring:
  config:
    activate.on-profile: swagger
springdoc:
  api-docs:
    enabled: true
    path: /api/v3/api-docs
  cache.disabled: true
  packagesToScan: edu.iu.uits.lms.etextmanager
  swagger-ui:
    enabled: false
    disable-swagger-default-url: true
    path: /api/swagger-ui.html
    # Setting supportedSubmitMethods to an empty list is what turns off the "try it out" button
    #    supportedSubmitMethods:
    oauth:
      clientId: ${oauth.tokenprovider.clientId}
  oAuthFlow:
    authorizationUrl: ${oauth.tokenprovider.url}/oauth/authorize
    tokenUrl: ${oauth.tokenprovider.accessTokenUri}