insert into ETEXT_TOOL_CONFIG (ETEXT_TOOL_CONFIG_ID, TOOL_NAME, TOOL_TYPE, CONTEXT_ID, JSON_BODY, CREATEDON, MODIFIEDON)
    values ('1', 'root_hidden', 'ROOT_13_PLACEMENT', '1234', '{"canvas_tab": {"hidden":true}}', '2024-02-26 13:13:13', '2024-02-26 13:13:13');

insert into ETEXT_TOOL_CONFIG (ETEXT_TOOL_CONFIG_ID, TOOL_NAME, TOOL_TYPE, CONTEXT_ID, JSON_BODY, CREATEDON, MODIFIEDON)
    values ('2', 'root_visible', 'ROOT_13_PLACEMENT', '7777', '{"canvas_tab": {"hidden":false}}', '2024-02-26 13:13:13', '2024-02-26 13:13:13');

insert into ETEXT_TOOL_CONFIG (ETEXT_TOOL_CONFIG_ID, TOOL_NAME, TOOL_TYPE, CONTEXT_ID, JSON_BODY, CREATEDON, MODIFIEDON)
    values ('3', 't1', 'ROOT_13_PLACEMENT', '7777', '{"canvas_tab": {"hidden":false}}', '2024-02-26 13:13:13', '2024-02-26 13:13:13');

insert into ETEXT_TOOL_CONFIG (ETEXT_TOOL_CONFIG_ID, TOOL_NAME, TOOL_TYPE, CONTEXT_ID, JSON_BODY, CREATEDON, MODIFIEDON)
    values ('4', 't2', 'ROOT_13_PLACEMENT', '7777', '{"canvas_tab": {"hidden":false}}', '2024-02-26 13:13:13', '2024-02-26 13:13:13');

insert into ETEXT_TOOL_CONFIG (ETEXT_TOOL_CONFIG_ID, TOOL_NAME, TOOL_TYPE, CONTEXT_ID, JSON_BODY, CREATEDON, MODIFIEDON)
    values ('5', 't3', 'ROOT_13_PLACEMENT', '7777', '{"canvas_tab": {"hidden":false}}', '2024-02-26 13:13:13', '2024-02-26 13:13:13');

insert into ETEXT_RESULTS_BATCH (ETEXT_RESULTS_BATCH_ID, UPLOADER, RUN_DATE)
    values ('1', 'user1', '2024-05-20 08:08:08');

insert into ETEXT_RESULTS (ETEXT_RESULT_ID, ETEXT_RESULTS_BATCH_ID, TOOL, FILENAME, TOOL_ID, SIS_COURSE_ID, CANVAS_COURSE_ID, DEPLOYMENT_ID, MESSAGE, ARCHIVED, STATUS, INPUT_PRESSBOOK_TITLE, INPUT_PRESSBOOK_LINK)
    values ('1', '1', 't1', 'file1.csv', 'tool_1', 'FA24-asdf-1234', '12345', 'deployment_1', 'success', false, 'SUCCESS', null, null);

insert into ETEXT_RESULTS (ETEXT_RESULT_ID, ETEXT_RESULTS_BATCH_ID, TOOL, FILENAME, TOOL_ID, SIS_COURSE_ID, CANVAS_COURSE_ID, DEPLOYMENT_ID, MESSAGE, ARCHIVED, STATUS, INPUT_PRESSBOOK_TITLE, INPUT_PRESSBOOK_LINK)
    values ('2', '1', 't2', 'file1.csv', 'tool_2', 'FA24-asdf-1234', '12345', 'deployment_2', 'success', false, 'SUCCESS', null, null);

insert into ETEXT_RESULTS (ETEXT_RESULT_ID, ETEXT_RESULTS_BATCH_ID, TOOL, FILENAME, TOOL_ID, SIS_COURSE_ID, CANVAS_COURSE_ID, DEPLOYMENT_ID, MESSAGE, ARCHIVED, STATUS, INPUT_PRESSBOOK_TITLE, INPUT_PRESSBOOK_LINK)
    values ('3', '1', 't3', 'file2.csv', 'tool_3', 'FA24-asdf-1234', '12345', 'deployment_3', 'uh oh', false, 'FAIL', null, null);


insert into ETEXT_RESULTS_BATCH (ETEXT_RESULTS_BATCH_ID, UPLOADER, RUN_DATE)
    values ('2', 'user2', '2024-05-21 08:08:08');

insert into ETEXT_RESULTS (ETEXT_RESULT_ID, ETEXT_RESULTS_BATCH_ID, TOOL, FILENAME, TOOL_ID, SIS_COURSE_ID, CANVAS_COURSE_ID, DEPLOYMENT_ID, MESSAGE, ARCHIVED, STATUS, INPUT_PRESSBOOK_TITLE, INPUT_PRESSBOOK_LINK)
    values ('4', '2', 't1', 'file1.csv', 'tool_1', 'FA24-asdf-1234', '12345', 'deployment_1', 'uh oh', false, 'FAIL', null, null);

insert into ETEXT_RESULTS (ETEXT_RESULT_ID, ETEXT_RESULTS_BATCH_ID, TOOL, FILENAME, TOOL_ID, SIS_COURSE_ID, CANVAS_COURSE_ID, DEPLOYMENT_ID, MESSAGE, ARCHIVED, STATUS, INPUT_PRESSBOOK_TITLE, INPUT_PRESSBOOK_LINK)
    values ('5', '2', 't2', 'file1.csv', 'tool_2', 'FA24-asdf-1234', '12345', 'deployment_2', 'success', false, 'SUCCESS', null, null);

insert into ETEXT_RESULTS (ETEXT_RESULT_ID, ETEXT_RESULTS_BATCH_ID, TOOL, FILENAME, TOOL_ID, SIS_COURSE_ID, CANVAS_COURSE_ID, DEPLOYMENT_ID, MESSAGE, ARCHIVED, STATUS, INPUT_PRESSBOOK_TITLE, INPUT_PRESSBOOK_LINK)
    values ('6', '2', 't3', 'file2.csv', 'tool_3', 'FA24-asdf-1234', '12345', 'deployment_3', 'success', false, 'SUCCESS', null, null);


insert into ETEXT_RESULTS_BATCH (ETEXT_RESULTS_BATCH_ID, UPLOADER, RUN_DATE)
    values ('3', 'user1', '2024-05-22 08:08:08');

insert into ETEXT_RESULTS (ETEXT_RESULT_ID, ETEXT_RESULTS_BATCH_ID, TOOL, FILENAME, TOOL_ID, SIS_COURSE_ID, CANVAS_COURSE_ID, DEPLOYMENT_ID, MESSAGE, ARCHIVED, STATUS, INPUT_PRESSBOOK_TITLE, INPUT_PRESSBOOK_LINK)
    values ('7', '3', 't1', 'file1.csv', 'tool_1', 'FA24-asdf-1234', '12345', 'deployment_1', 'uh oh', true, 'FAIL', null, null);

insert into ETEXT_RESULTS (ETEXT_RESULT_ID, ETEXT_RESULTS_BATCH_ID, TOOL, FILENAME, TOOL_ID, SIS_COURSE_ID, CANVAS_COURSE_ID, DEPLOYMENT_ID, MESSAGE, ARCHIVED, STATUS, INPUT_PRESSBOOK_TITLE, INPUT_PRESSBOOK_LINK)
    values ('8', '3', 't2', 'file1.csv', 'tool_2', 'FA24-asdf-1234', '12345', 'deployment_2', 'uh oh', false, 'FAIL', null, null);

insert into ETEXT_RESULTS (ETEXT_RESULT_ID, ETEXT_RESULTS_BATCH_ID, TOOL, FILENAME, TOOL_ID, SIS_COURSE_ID, CANVAS_COURSE_ID, DEPLOYMENT_ID, MESSAGE, ARCHIVED, STATUS, INPUT_PRESSBOOK_TITLE, INPUT_PRESSBOOK_LINK)
    values ('9', '3', 't3', 'file2.csv', 'tool_3', 'FA24-asdf-1234', '12345', 'deployment_3', 'success', false, 'SUCCESS', null, null);
